import { test, expect } from '@playwright/test';
test('search, favorites and theme persist', async ({ page }) => {
 await page.goto('./');
 await expect(page.locator('.tool-card')).toHaveCount(53);
 await page.locator('#search').fill('uuid');
 await expect(page.locator('.tool-card')).toHaveCount(1);
 await page.getByRole('button', {name: 'Favorite UUID Generator',exact:true}).click();
 await page.locator('#theme').click();
 await page.reload();
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.locator('[data-view="Favorites"]').click();
 await expect(page.locator('.tool-card')).toHaveCount(1);
 await expect(page.locator('.tool-card')).toContainText('UUID Generator');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('all converters run and hash routes survive reload', async ({page}) => {
 await page.goto('./#tool/encoding-converter');
 await page.locator('#input').fill('नमस्ते 👋');
 await page.locator('#run-tool').click();
 const encoded=await page.locator('#result').inputValue();
 await page.locator('#mode').selectOption('base64-decode');
 await page.locator('#input').fill(encoded);
 await page.locator('#run-tool').click();
 await expect(page.locator('#result')).toHaveValue('नमस्ते 👋');
 await page.locator('#input').fill('%%%');
 await page.locator('#run-tool').click();
 await expect(page.locator('#result')).toHaveValue('');
 await page.locator('#close').click();
 await page.locator('[data-open="unit-converter"]').click();
 await page.locator('#dimension').selectOption('Temperature');
 await page.locator('#input').fill('100');
 await page.locator('#run-tool').click();
 await expect(page.locator('#result')).toHaveValue('212 Fahrenheit');
 await page.reload();
 await expect(page.locator('dialog')).toBeVisible();
 await expect(page.locator('#tool-title')).toHaveText('Unit Converter');
 await page.locator('#close').click();
 await page.locator('[data-open="uuid-generator"]').click();
 await page.locator('#count').fill('3');
 await page.locator('#run-tool').click();
 expect((await page.locator('#result').inputValue()).split('\n')).toHaveLength(3);
 await page.locator('#close').click();
 await page.locator('[data-open="timestamp-converter"]').click();
 await page.locator('#input').fill('0');
 await page.locator('#run-tool').click();
 await expect(page.locator('#result')).toHaveValue(/1970-01-01T00:00:00.000Z/);
});
test('original tools still work after closing a converter', async ({page})=>{
 await page.goto('./#tool/unit-converter');
 await page.locator('#close').click();
 await page.locator('[data-open="text-workbench"]').click();
 await page.locator('#input').fill('hello world');
 await page.getByRole('button',{name:'UPPERCASE',exact:true}).click();
 await expect(page.locator('#input')).toHaveValue('HELLO WORLD');
 await page.locator('#close').click();
 await page.locator('[data-open="json-formatter"]').click();
 await page.locator('#input').fill('{"a":1}');
 await page.getByRole('button',{name:'Format JSON',exact:true}).click();
 await expect(page.locator('#result')).toHaveValue('{\n  "a": 1\n}');
 await page.locator('#close').click();
 await page.locator('[data-open="password-generator"]').click();
 await expect(page.locator('#result')).toHaveValue(/.{20}/);
});
