import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { parseZip, extractEntry, buildZip } from '../../src/tools/media-files/zip-tool/logic.js';
const axe = async page => (await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) }));
const fitsWidth = page => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
async function download(page, locator) { const pending = page.waitForEvent('download'); await locator.click(); const file = await pending, chunks = []; for await (const c of await file.createReadStream()) chunks.push(c); return { name: file.suggestedFilename(), bytes: new Uint8Array(Buffer.concat(chunks)) }; }
test.beforeEach(async ({ page }) => { page.errors = []; page.on('pageerror', e => page.errors.push(e.message)); });
test.afterEach(async ({ page }) => { expect(page.errors).toEqual([]); });
test('ZIP creator bundles files, renames duplicates, and produces a valid archive', async ({ page }) => {
 await page.goto('./#tool/zip-tool'); await page.reload();
 await expect(page.locator('#zip-build')).toBeDisabled();
 await page.locator('#zip-files').setInputFiles([{ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('hello '.repeat(400)) }, { name: 'photo.bin', mimeType: 'application/octet-stream', buffer: Buffer.from([1, 2, 3, 4]) }]);
 await page.locator('#zip-files').setInputFiles([{ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('second') }]);
 await expect(page.locator('#zip-chosen')).toHaveText('3 files · 2.4 KiB');
 await page.getByRole('button', { name: 'Remove photo.bin' }).click(); await expect(page.locator('#zip-list li')).toHaveCount(2);
 await page.locator('#zip-name').fill('my files'); await page.locator('#zip-build').click();
 await expect(page.locator('#feedback')).toContainText('ZIP ready: 2 files'); await expect(page.locator('#feedback')).toContainText('1 name was adjusted');
 const zip = await download(page, page.locator('#zip-download'));
 expect(zip.name).toBe('my files.zip');
 const entries = parseZip(zip.bytes);
 expect(entries.map(e => [e.name, e.method])).toEqual([['notes.txt', 8], ['notes (2).txt', 0]]);
 expect(Buffer.from(await extractEntry(zip.bytes, entries[1])).toString()).toBe('second');
 await page.locator('#zip-compress').uncheck(); await expect(page.locator('#zip-download')).toBeHidden();
 expect(await axe(page)).toEqual([]); expect(await fitsWidth(page)).toBe(true);
});
test('ZIP extractor lists entries, extracts with checksum, and rejects bad files', async ({ page }) => {
 const archive = await buildZip([{ name: 'docs/readme.md', data: new TextEncoder().encode('# Hi '.repeat(100)) }, { name: 'data/<b>tag</b>.json', data: new TextEncoder().encode('{"a":1}') }]);
 await page.goto('./#tool/zip-tool');
 await page.getByLabel('Open a ZIP').check(); await expect(page.locator('#zip-create')).toBeHidden();
 await page.locator('#zip-archive').setInputFiles({ name: 'sample.zip', mimeType: 'application/zip', buffer: Buffer.from(archive.bytes) });
 await expect(page.locator('#zip-summary')).toHaveText('2 files · 507 B uncompressed');
 await expect(page.locator('#zip-entries tbody tr')).toHaveCount(2); await expect(page.locator('#zip-entries')).toContainText('data/<b>tag</b>.json');
 const file = await download(page, page.getByRole('button', { name: 'Download docs/readme.md' }));
 expect(file.name).toBe('readme.md'); expect(Buffer.from(file.bytes).toString()).toBe('# Hi '.repeat(100));
 await expect(page.locator('#feedback')).toContainText('checksum verified');
 await page.locator('#zip-filter').fill('json'); await expect(page.locator('#zip-entries tbody tr')).toHaveCount(1);
 expect(await axe(page)).toEqual([]);
 await page.locator('#zip-archive').setInputFiles({ name: 'fake.zip', mimeType: 'application/zip', buffer: Buffer.from('definitely not a zip file here') });
 await expect(page.locator('#feedback')).toHaveText('This is not a ZIP file, or it is damaged.'); await expect(page.locator('#zip-entries')).toBeHidden();
 expect(await fitsWidth(page)).toBe(true);
});
test('quiz builder saves, runs, scores, and tracks best attempts', async ({ page }) => {
 await page.goto('./#tool/quiz-builder');
 await expect(page.locator('#quiz-status')).toHaveText('Save a quiz below to take it here.');
 await expect(page.locator('#record-questions')).toHaveValue(/Q: What is the capital of Japan\?/);
 await page.locator('#record-title').fill('Bad'); await page.locator('#record-questions').fill('Q: missing answer\n- a\n- b'); await page.locator('#save-record').click();
 await expect(page.locator('#feedback')).toContainText('needs at least one correct option'); await expect(page.locator('.saved-record')).toHaveCount(0);
 await page.locator('#record-title').fill('Geography'); await page.locator('#record-questions').fill('Q: What is the capital of Japan?\n- Osaka\n* Tokyo\n- Kyoto\n\nQ: Which of these are prime numbers?\n* 2\n* 7\n- 9\n- 15');
 await page.locator('#save-record').click();
 await expect(page.locator('.saved-record')).toContainText('2 questions · 0 attempts');
 await page.locator('#quiz-start').click();
 await expect(page.locator('.quiz-question')).toHaveCount(2); await expect(page.locator('.quiz-question').nth(1)).toContainText('(choose all that apply)');
 await page.getByRole('radio', { name: 'Tokyo' }).check(); await page.getByRole('checkbox', { name: '2', exact: true }).check();
 await page.locator('#quiz-submit').click();
 await expect(page.locator('#quiz-status')).toHaveText('Score: 1 of 2 (50%).');
 await expect(page.locator('.quiz-wrong .quiz-result')).toHaveText('✗ Correct answers: 2, 7');
 await expect(page.locator('#quiz-questions input').first()).toBeDisabled();
 expect(await axe(page)).toEqual([]);
 await page.locator('#quiz-retry').click();
 await page.getByRole('radio', { name: 'Tokyo' }).check(); page.once('dialog', d => d.accept()); await page.locator('#quiz-submit').click();
 await expect(page.locator('#quiz-status')).toHaveText('Score: 1 of 2 (50%).');
 await page.locator('#quiz-retry').click();
 await page.getByRole('radio', { name: 'Tokyo' }).check(); await page.getByRole('checkbox', { name: '2', exact: true }).check(); await page.getByRole('checkbox', { name: '7', exact: true }).check();
 await page.locator('#quiz-submit').click(); await expect(page.locator('#quiz-status')).toHaveText('Score: 2 of 2 (100%).');
 await page.reload();
 await expect(page.locator('.saved-record')).toContainText('2 questions · 3 attempts · best 100%');
 await expect(page.locator('#quiz-select option')).toHaveText('Geography (best 100%)');
 await page.getByRole('button', { name: 'Edit', exact: true }).click(); await page.locator('#record-questions').fill('Q: New?\n* yes\n- no'); await page.locator('#save-record').click();
 await expect(page.locator('.saved-record')).toContainText('1 question · 0 attempts');
 expect(await fitsWidth(page)).toBe(true);
});
test('quiz and ZIP tools pass accessibility checks in dark theme', async ({ page }) => {
 await page.goto('./'); await page.locator('#theme').click();
 await page.locator('[data-open="quiz-builder"]').click(); await page.locator('#record-title').fill('T'); await page.locator('#save-record').click(); await page.locator('#quiz-start').click();
 await page.getByRole('radio', { name: 'Osaka' }).check(); page.once('dialog', d => d.accept()); await page.locator('#quiz-submit').click();
 await expect(page.locator('.quiz-wrong')).toHaveCount(2); expect(await axe(page)).toEqual([]);
 await page.locator('#close').click(); await page.locator('[data-open="zip-tool"]').click(); expect(await axe(page)).toEqual([]);
});
