import test from 'node:test';
import assert from 'node:assert/strict';
import { diffLines, unifiedText, MAX_DIFF_LINES } from '../../src/tools/text/text-diff/logic.js';
import { testRegex, describeMatches, buildRegex } from '../../src/tools/developer/regex-tester/logic.js';
import { parseMarkdown, toHTML, safeHref, parseInline } from '../../src/tools/text/markdown-editor/logic.js';
import { zonedInstants, planMeeting, formatOffset, offsetMinutes } from '../../src/tools/travel/time-zone-planner/logic.js';
import { cents, parseItems, planBudget, describeBudget } from '../../src/tools/finance/budget-planner/logic.js';
test('text diff finds minimal line changes and honours ignore options', () => {
 const result = diffLines('a\nb\nc\nd', 'a\nB\nc\nd\ne');
 assert.equal(unifiedText(result), '  a\n- b\n+ B\n  c\n  d\n+ e');
 assert.deepEqual([result.added, result.removed, result.unchanged], [2, 1, 3]);
 assert.equal(diffLines('a\r\nb\n', 'a\nb').identical, true);
 assert.equal(diffLines('Hello  World', ' hello world ', { ignoreWhitespace: true, ignoreCase: true }).identical, true);
 assert.equal(diffLines('Hello', 'hello').identical, false);
 assert.deepEqual(diffLines('', 'x').ops.map(op => op.type), ['add']);
 assert.deepEqual(diffLines('x', '').ops.map(op => op.type), ['remove']);
 const numbered = diffLines('1\n2\n3', '1\n3');
 assert.deepEqual(numbered.ops.map(op => [op.type, op.oldLine, op.newLine]), [['equal', 1, 1], ['remove', 2, null], ['equal', 3, 2]]);
 assert.throws(() => diffLines('x\n'.repeat(MAX_DIFF_LINES + 1), ''), /limited/);
 assert.throws(() => diffLines(Array.from({ length: 3000 }, (_, i) => `a${i}`).join('\n'), Array.from({ length: 3000 }, (_, i) => `b${i}`).join('\n')), /differ too much/);
});
test('regex tester lists matches, groups, named groups, and replacements', () => {
 const result = testRegex('(?<user>\\w+)@(\\w+)\\.com', 'gi', 'a@x.com, B@Y.COM', '$2');
 assert.equal(result.count, 2);
 assert.deepEqual(result.matches[1], { index: 9, end: 16, value: 'B@Y.COM', groups: ['B', 'Y'], named: { user: 'B' } });
 assert.equal(result.replaced, 'x, Y');
 assert.equal(testRegex('a', '', 'aaa', 'b').replaced, 'baa');
 assert.equal(testRegex('a', '', 'aaa').count, 1);
 assert.match(describeMatches(testRegex('a', '', 'aaa')), /first match only/);
 assert.equal(testRegex('x*', 'g', 'ab').count, 3);
 assert.equal(testRegex('(?:)', 'gu', '😀a').count, 3);
 assert.equal(testRegex('(a)|b', 'g', 'b').matches[0].groups[0], null);
 assert.equal(testRegex('a', 'g', 'a'.repeat(1500)).truncated, true);
 assert.equal(describeMatches(testRegex('z', 'g', 'abc')), 'No matches.');
 for (const [pattern, flags] of [['', 'g'], ['(', 'g'], ['a', 'gg'], ['a', 'x']]) assert.throws(() => buildRegex(pattern, flags));
});
test('markdown renders a safe subset and escapes raw HTML', () => {
 const html = toHTML(parseMarkdown('# Title *it*\n\nA **b** `<c>` ~~d~~ [ok](https://e.x) [bad](javascript:x)\n<script>alert(1)</script>\n\n- [x] done\n- open\n\n3. three\n\n> quote\n\n```js\n<b>&\n```\n\n---'));
 assert.equal(html, '<h1>Title <em>it</em></h1>\n<p>A <strong>b</strong> <code>&lt;c&gt;</code> <del>d</del> <a href="https://e.x">ok</a> bad\n&lt;script&gt;alert(1)&lt;/script&gt;</p>\n<ul>\n<li><input type="checkbox" disabled checked> done</li>\n<li>open</li>\n</ul>\n<ol start="3">\n<li>three</li>\n</ol>\n<blockquote>\n<p>quote</p>\n</blockquote>\n<pre><code class="language-js">&lt;b&gt;&amp;\n</code></pre>\n<hr>'.replace('&amp;\n</code>', '&amp;</code>'));
 for (const href of ['javascript:alert(1)', 'data:text/html,x', ' vbscript:x', '//evil.example']) assert.equal(safeHref(href), null);
 assert.equal(safeHref('mailto:a@b.c'), 'mailto:a@b.c');
 assert.deepEqual(parseInline('snake_case_name \\*literal\\*'), [{ type: 'text', value: 'snake_case_name *literal*' }]);
 assert.throws(() => parseMarkdown('x'.repeat(200001)));
});
test('time zone planner handles offsets, DST gaps, overlaps, and day shifts', () => {
 assert.deepEqual(zonedInstants('2026-01-15', '09:00', 'Asia/Kolkata'), [Date.UTC(2026, 0, 15, 3, 30)]);
 assert.deepEqual(zonedInstants('2026-03-08', '02:30', 'America/New_York'), []);
 assert.deepEqual(zonedInstants('2026-11-01', '01:30', 'America/New_York'), [Date.UTC(2026, 10, 1, 5, 30), Date.UTC(2026, 10, 1, 6, 30)]);
 assert.equal(offsetMinutes(Date.UTC(2026, 6, 1), 'Asia/Kathmandu'), 345);
 assert.equal(formatOffset(-210), 'UTC−03:30');
 const plan = planMeeting('2026-09-25', '23:00', 'Asia/Kolkata', ['America/Los_Angeles', 'Pacific/Kiritimati', 'UTC']);
 assert.equal(plan.utc, '2026-09-25T17:30:00.000Z');
 assert.deepEqual(plan.rows.map(r => [r.time, r.dayShift, r.working]), [['10:30', 0, true], ['07:30', 1, false], ['17:30', 0, false]]);
 assert.equal(planMeeting('2026-11-01', '01:30', 'America/New_York', ['UTC']).ambiguous, true);
 assert.throws(() => planMeeting('2026-03-08', '02:30', 'America/New_York', ['UTC']), /does not exist/);
 assert.throws(() => planMeeting('2026-02-30', '09:00', 'UTC', ['UTC']));
 assert.throws(() => planMeeting('2026-01-01', '09:00', 'Mars/Olympus', ['UTC']), /Unknown time zone/);
 assert.throws(() => planMeeting('2026-01-01', '09:00', 'UTC', ['', ' ']), /at least one/);
});
test('budget planner uses exact cents and the 50/30/20 comparison', () => {
 assert.equal(cents('1,234.5', 'x'), 123450); assert.equal(cents('0.1', 'x') + cents('0.2', 'x'), 30);
 for (const bad of ['-1', '1.234', 'abc', '']) assert.throws(() => cents(bad, 'Amount'));
 assert.deepEqual(parseItems('Rent, 10\nFun; 2; wants\nETF\t3\tsavings').map(i => i.group), ['need', 'want', 'saving']);
 assert.throws(() => parseItems('Rent'), /Line 1/); assert.throws(() => parseItems('Rent, 1, luxury'), /group/); assert.throws(() => parseItems(''), /at least one/);
 const plan = planBudget('1000', 'Rent, 500.10\nFun, 300, want\nSave, 199.90, saving');
 assert.deepEqual([plan.allocated, plan.remaining, plan.totals.need], [100000, 0, 50010]);
 const text = describeBudget(plan);
 assert.match(text, /Needs: 500\.10 \(50\.0%\) vs 50% = 500\.00 · 0\.10 above/); assert.match(text, /Savings: 199\.90 .* 0\.10 below/);
 assert.match(describeBudget(planBudget('100', 'Rent, 150')), /Over budget by: 50\.00/);
 assert.throws(() => planBudget('0', 'Rent, 1'), /greater than zero/);
});
